### ISSUE TITLE
Name of read-write attribute?

### ISSUE THREAD

**Issue by martinvw** [michaelpq/michaelpq.github.io#5]
https://github.com/michaelpq/michaelpq.github.io/blob/master/_posts/2016-12-09-postgres-10-libpq-read-write.markdown

Hello,

Based upon your blog I was looking into connecting to the master in a cluster setup but it seems that property documented in your blog does not work anymore in the final 10 release?

In the end I just followed the official docs and use `targetServerType`

Wdyt?

**Comment by michaelpq** [comment]
targetServerType is not part of PostgreSQL's connection string options, and as the blog mentions, the option is documented here:
https://www.postgresql.org/docs/devel/static/libpq-connect.html#libpq-connect-target-session-attrs
Perhaps you are using pgpool or the Postgres JDBC driver? I see no problems in the post or the documentation.

**Comment by martinvw** [comment]
Indeed I incorrectly assumed it was a jdbc connection string and thus was talking about usage with the Postgres JDBC Driver. Thanks for clearing this up!
